apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: certmanager
    repoURL: https://github.com/ricsanfre/argocd-tests
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
