apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd-control-plane
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.9.4
    helm:
      parameters:
      - name: identity.externalCA
        value: "true"
      - name: identity.issuer.scheme
        value: kubernetes.io/tls
      - name: disableHeartBeat
        value: "true"
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
