apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd-crds
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.4.0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: authorizationpolicies.policy.linkerd.io
      jsonPointers:
      - /spec/names/shortNames
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: meshtlsauthentications.policy.linkerd.io
      jsonPointers:
      - /spec/names/shortNames
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: networkauthentications.policy.linkerd.io
      jsonPointers:
      - /spec/names/shortNames

